
version: 2

models:
  - name: MAIN_EXAMPLE
    description: "A starter dbt model"
    columns:
      - name: C_CUSTKEY
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: A_CUSTKEY
        description: "Secondary Column"
        tests:
          - unique
          - not_null

  - name: DEPENDS_ON_EXAMPLE
    description: "A starter dbt model"
    columns:
      - name: C_CUSTKEY
        description: "The primary key for this table"
        tests:
          - not_null

  - name: SECOND_DEPENDS_ON_EXAMPLE
    description: "A starter dbt model"
    columns:
      - name: C_CUSTKEY
        description: "The primary key for this table"
        tests:

  - name: SOURCE_EXAMPLE
    description: "A starter dbt model"
    columns:
      - name: C_CUSTKEY
        description: "The primary key for this table"
        tests:

sources:
  - name: test_source
    tables:
      - name: MELIK_CUSTOMER
      - name: MELIK_ORDERS

metrics:
  - name: test_metrics
    label: metrics
    model: ref('DEPENDS_ON_EXAMPLE')
    description: "Total revenue from orders in the specified time period"

    type: sum
    sql: net_item_sales_amount

    timestamp: order_date
    time_grains: [ day, week, month, quarter, year ]

    dimensions:
      - priority_code

