
version: 2

models:
  - name: MELIK_CUSTOMER
    description: "A starter dbt model"
    columns:
      - name: C_CUSTKEY
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: A_CUSTKEY
        description: "Secondary Column"
        tests:
          - unique
          - not_null

  - name: MELIK_ORDERS
    description: "A starter dbt model"
    columns:
      - name: C_CUSTKEY
        description: "The primary key for this table"
        tests:
          - not_null

  - name: MELIK_ORDERS_TWO
    description: "A starter dbt model"
    columns:
      - name: C_CUSTKEY
        description: "The primary key for this table"
        tests:

  - name: MELIK_ORDERS3
    description: "A starter dbt model"
    columns:
      - name: C_CUSTKEY
        description: "The primary key for this table"
        tests:

sources:
  - name: test_source
    tables:
      - name: MELIK_CUSTOMER
      - name: MELIK_ORDERS
