
version: 2

models:
    - name: customer
      description: "A starter dbt model"
      columns:
          - name: C_CUSTKEY
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: orders
      description: "A starter dbt model"
      columns:
          - name: O_CUSTKEY
            description: "The primary key for this table"
            tests:
                - not_null

    - name: customers
        description: "A starter dbt model"
        columns:
          - name: O_CUSTKEY
            description: "The primary key for this table"
            tests:
              - not_null